name = "StoThyLiveCell"
uuid = "c209c10c-a2a7-4006-b072-270167cfcc8e"
authors = ["Gregory Roth"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
